- background image
- readonly
- value
- keyboards
- does clearOnResize need to observer?
- change event
- rescale based on window.devicePixelRatio
- getTrimmedCanvas
- examples for:
  - dotSize
  - throttle
  - velocity
  - plusAfter
  - plusBefore
  - plusEnd
  - plusStart
  - canvas
  - fromData
  - fromDataURL
  - isEmpty
  - toData
  - toDataURL
  - toSVG
  - resize
