- add margin and its css varibale
- do we need these properties for `aria-orientation=horizontal`
  - min-height: auto
  - width: auto
  - min-width: 100%
- do we need these properties for `aria-orientation=vertical`
  - min-width: auto
- add shadow example
  - https://uicookies.com/css-divider/
  - https://devdevout.com/css/css-gradient-borders
  - https://devsnap.me/css-border-examples
- Placement like MUI
