name: 💡 Feature Request
description: "Suggest a new feature or enhancement for the project."
labels: ["enhancement"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        **Thank you for suggesting a new feature! 🎉**

        Please take a moment to describe your idea in detail so we can understand it fully. Check if a similar feature request exists before submitting, as this helps us keep discussions organized. 💡

        Our team of dedicated volunteers appreciates the time you spend on this! With your input, we can make this project even better. Thank you for helping us grow! 🌱❤️
  - type: textarea
    id: description
    attributes:
      label: Description
      description: "Describe the feature in detail, including why it's valuable."
      required: true

  - type: textarea
    id: use_case
    attributes:
      label: Use Case
      description: "Describe a scenario where this feature would be useful."
      placeholder: "Explain how this feature would improve the user experience..."

  - type: textarea
    id: proposed_solution
    attributes:
      label: Proposed Solution
      description: "Describe how you envision this feature being implemented."
      placeholder: "Provide ideas or suggestions for implementation..."

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: "Add any other context or screenshots that might help explain your request."
      placeholder: "Include any other details here..."