import {
  Element,
  ElementPropertiesAutoGenerated,
  Overrides,
  OverridesConfig,
  Property,
  Provider
} from '@htmlplus/element';

import { PlusCore } from '@/core';
import { Breakpoint } from '@/types';

/**
 * @subset
 *
 * @slot default - The default slot.
 */
@Element()
export class Accordions extends PlusCore {
  /**
   * Specifies that only one accordion can be open.
   */
  @Property()
  persistent?: boolean;

  /**
   * TODO
   */
  @Property()
  @Overrides()
  overrides?: OverridesConfig<Breakpoint, ElementPropertiesAutoGenerated>;

  @Provider('accordions')
  get state(): any {
    return {
      open: this.open.bind(this)
    };
  }

  open(target: HTMLElement) {
    if (!this.persistent) return;

    for (const accordion of Array.from(this.$host.children)) {
      if (accordion === target) continue;

      if (!accordion['open']) continue;

      accordion.shadowRoot.querySelector('[part=header]')['click']();
    }
  }

  render() {
    return <slot />;
  }
}
