name: 🐛 Bug report
description: Report a bug or an issue with the project.
labels: [ "bug" ]
assignees: [ ]

body:
  - type: markdown
    attributes:
      value: |
        Thank you for opening an issue! 😄

        Before diving in, please take a quick look at existing issues — your question might already have been answered! 🔍✨

        We're a team of passionate volunteers, so by providing clear and detailed info, you're helping us help you faster. Your contribution is greatly appreciated! ❤️

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide detailed information about the bug. If you have screenshots or videos, drag and drop them here. You can also upload your code to a service like CodeSandbox and include the link for reference.
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Provide a step-by-step guide on how to reproduce the bug.
      placeholder: "1. Go to '...'\n2. Click on '...'\n3. See error"

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: Describe what you expected to happen instead of the bug.

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: Explain what happened instead of the expected behavior.

  - type: input
    id: browser
    attributes:
      label: Browser
      description: Specify the browser and its version where the bug occurs.
      placeholder: e.g., Chrome 95, Firefox 92, Safari 15

  - type: input
    id: framework
    attributes:
      label: Framework
      description: Specify the framework/library and its version where the bug occurs.
      placeholder: e.g., React 18, Angular 15, Vue 3

  - type: dropdown
    id: language
    attributes:
      label: Programming Language
      options:
        - JavaScript
        - TypeScript